[env:esp32dev]
src_filter = +<main.cpp>
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Libraries
lib_deps =
    https://github.com/avishorp/TM1637.git
    arduino-libraries/NTPClient @ ^3.2.1

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=1
