[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Libraries
lib_deps =
    avishorp/TM1637TubeClockDisplay @ ^1.0.0
    arduino-libraries/NTPClient @ ^3.2.1

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=1
